### ISSUE TITLE
No percentages

### ISSUE THREAD

**Issue by tuncbkose** [delphiki/gnome-airpods-battery-status#1]
AirStatus seem to work, running main.py I can see charge levels. For some reason, I can't see the percentages on the top bar. Any suggestions on how to debug this? I am running Gnome 3.38.5 and Pop_OS 21.04.

**Comment by delphiki** [comment]
Hi, 
Do you at least have the icons showing up?

**Comment by Movisivi** [comment]
Icons show up but no percentage

**Comment by Movisivi** [comment]
I am on Arch Linux 5.15.14-1-lts

**Comment by Movisivi** [comment]
Working now. https://github.com/delphiki/AirStatus/issues/3#issuecomment-1019431135
