### ISSUE TITLE
[TODO] Add compatibility for Gnome 43

### ISSUE THREAD

**Issue by delphiki** [delphiki/gnome-airpods-battery-status#9]
The extension is broken on Gnome 43.

I'll try to update it asap.

**Comment by lucaliceti** [comment]
Would love to know when issue if fixed. Thank you!

**Comment by voedev** [comment]
Would love to know when issue if fixed. Thank you!

**Comment by delphiki** [comment]
Yes, sorry for the lack of feedback, this is still a WIP.
I've reworked a bit the way the extension works, and added a few information in a submenu, but it still needs some work before being released.

![Capture d’écran du 2023-02-16 16-28-42](https://user-images.githubusercontent.com/303778/219412129-d52feeba-7bb0-4fd5-9bd7-4eff54f9a2a9.png)

![Capture d’écran du 2023-02-16 16-34-04](https://user-images.githubusercontent.com/303778/219412709-c7ed2d5e-e7fd-4322-a942-cb8bd66afae3.png)

**Comment by lucaliceti** [comment]
I the extension still on https://extensions.gnome.org/, I can't find it?

**Comment by delphiki** [comment]
> I the extension still on https://extensions.gnome.org/, I can't find it?

By default, the list is filtered and only shows extensions compatible with your gnome shell version, but yes, it still there: https://extensions.gnome.org/extension/3736/airpods-battery-status/

**Comment by rainyskye** [comment]
Hey @delphiki - has there been any progress on the Gnome 43 bringup? Or is any help wanted?

Cheers :)

**Comment by lucaliceti** [comment]
It still shows up as INCOMPATIBLE when trying to install it from the gnome extensions website.

**Comment by rainyskye** [comment]
> It still shows up as INCOMPATIBLE when trying to install it from the gnome extensions website.

Yeah? It hasn't been updated yet. The fix is currently in development.

**Comment by voedev** [comment]
Waiting for gnome 43... Gnome 44 will be released relatively soon :)

**Comment by delphiki** [comment]
I made some progress yesterday evening, here is what it'll look like:
![Capture d’écran du 2023-03-23 16-07-52](https://user-images.githubusercontent.com/303778/227262550-d32f2169-71db-4aaf-bbba-fcef7a10bdc2.png)

I still have some random crashes I need to sort out, but I'll release it soon enough (hopefully by the end of the week).

**Comment by voedev** [comment]
> I made some progress yesterday evening, here is what it'll look like: ![Capture d’écran du 2023-03-23 16-07-52](https://user-images.githubusercontent.com/303778/227262550-d32f2169-71db-4aaf-bbba-fcef7a10bdc2.png)
> 
> I still have some random crashes I need to sort out, but I'll release it soon enough (hopefully by the end of the week).

Wow, looks great!  If that's really how this works then it's truly remarkable.👍 

Could you, please, tell me which linux distribution you use? I'm using fedora and, it's been for a few years now that they have this bug with displaying of  jetbrains toolbox application in the system tray. 

Will leave the link here (the discussions on this topic are still on), just in case you might want to check it out too: https://youtrack.jetbrains.com/issue/TBX-4785/JetBrains-ToolBox-does-not-show-in-system-tray-on-Fedora

I wonder which linux distribution you use and if you, maybe, also faced this problem and found a way to fix it?

**Comment by delphiki** [comment]
> Could you, please, tell me which linux distribution you use? I'm using fedora and, it's been for a few years now that they have this bug with displaying of jetbrains toolbox application in the system tray.
> 
> Will leave the link here (the discussions on this topic are still on), just in case you might want to check it out too: https://youtrack.jetbrains.com/issue/TBX-4785/JetBrains-ToolBox-does-not-show-in-system-tray-on-Fedora
> 
> I wonder which linux distribution you use and if you, maybe, also faced this problem and found a way to fix it?

I'm running Fedora 37 (and I've been using Fedora for years). I've never had this issue with the Jetbrains icon, I'm using Tray Icons: Reload and it works great :)

**Comment by delphiki** [comment]
I just released the new version!
It is currently in review on the gnome extensions website, but if you can't wait, you stil can install it manually :)

**Comment by voedev** [comment]
> I just released the new version! It is currently in review on the gnome extensions website, but if you can't wait, you stil can install it manually :)

Updated the extension, but for some reason AirStatus stopped working.

Decided to reinstall AirStatus:

```bash
git clone git@github.com:delphiki/AirStatus.git
cd AirStatus
pip3 install bleak
python3 main.py
```

The script doesn't output anything and just keeps running. Headphones connected

**Comment by delphiki** [comment]
> Updated the extension, but for some reason AirStatus stopped working.
> 
> Decided to reinstall AirStatus:
> 
> ```shell
> git clone git@github.com:delphiki/AirStatus.git
> cd AirStatus
> pip3 install bleak
> python3 main.py
> ```
> 
> The script doesn't output anything and just keeps running. Headphones connected

Did you check the Controller Mode in your bluetooth config (/etc/bluetooth/main.conf)?
It should be "dual".

**Comment by voedev** [comment]
> Did you check the Controller Mode in your bluetooth config (/etc/bluetooth/main.conf)? It should be "dual".

Thanks a lot, it helped!!
